# Generated by Django 5.1.2 on 2024-11-01 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_creation",
            field=models.DateField(
                default=datetime.date.today, verbose_name="fecha_creacion"
            ),
        ),
    ]
