# Generated by Django 5.1.2 on 2024-11-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_creation",
            field=models.DateField(auto_now_add=True, verbose_name="fecha_creacion"),
        ),
    ]
